[tool.poetry]
name = "custom_user_assessment"
version = "0.1.0"
description = ""
authors = ["mavrickwatts"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
django = "^3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
